version: "3.5"
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: postgres
      POSTGRES_DB: data
    volumes:
      - /data/softlab/postgres:/var/lib/postgresql/data
    ports:
      - "5430:5432"
volumes:
  postgres:
